version: "3"

networks:
  test-app:
    driver: bridge

services:
  app:
    build:
      args:
        user: pavel
        uid: 1001
      context: ../project
      dockerfile: ../project/Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8081:8081"
    container_name: project
    restart: on-failure
    networks:
      - test-app
  db:
    build:
      context: ./psql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5455:5432"
    env_file:
      - ./psql/conf/.env
    container_name: app_db
    networks:
      - test-app
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6364:6379"
    networks:
      - test-app
  rabbitmq:
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - ./rabbit/conf/.env
    restart: always
    networks:
      - test-app

volumes:
  dbdata:
    driver: local
